### ISSUE TITLE
crash on loading elec332?

### ISSUE THREAD

**Issue by popps73x** [Elec332/craftingtableiii#90]
trying to make my first modpack. it is 1.9 so i understand if this takes a while.  I believe this is your error but i may be wrong.  any help is appreciated thank you very much.

---- Minecraft Crash Report ----

WARNING: coremods are present:
  CodeChickenCorePlugin (CodeChickenCore-1.9-2.0.1.53-universal.jar)
  FldLoadingPlugin (FastLeafDecay-1.9-1.6.jar)
  LoadingPlugin (HardcoreDarkness-MC1.9-1.8.jar)
  LoadingPlugin (RandomThings-MC1.9-3.7.jar)
  Reborn Core ASM (RebornCore-1.9-2.1.0.53-universal.jar)
  CCCDeobfPlugin (unknown)
  FMLPlugin (InventoryTweaks-1.61-dev-49.jar)
  LoadingPlugin (Bloodmoon-MC1.9-1.4.1.jar)
  CCLCorePlugin (CodeChickenLib-1.9-2.0.1.23-universal.jar)
Contact their authors BEFORE contacting forge

// I feel sad now :(

Time: 5/7/16 7:54 AM
Description: Initializing game

java.lang.NoClassDefFoundError: mcmultipart/multipart/MultipartRegistry
	at elec332.core.client.newstuff.ElecModelHandler.registerMultiPartModels(ElecModelHandler.java:126)
	at elec332.core.proxies.ClientProxy$RenderReplacer$1.func_110549_a(ClientProxy.java:77)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110542_a(SimpleReloadableResourceManager.java:120)
	at elec332.core.client.model.ElecResourceManager.func_110542_a(ElecResourceManager.java:47)
	at elec332.core.proxies.ClientProxy$RenderReplacer.onRegister(ClientProxy.java:72)
	at elec332.core.client.model.ElecResourceManager.func_110542_a(ElecResourceManager.java:42)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:494)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:346)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: mcmultipart.multipart.MultipartRegistry
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 15 more
Caused by: java.lang.NullPointerException
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 17 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at elec332.core.client.newstuff.ElecModelHandler.registerMultiPartModels(ElecModelHandler.java:126)
	at elec332.core.proxies.ClientProxy$RenderReplacer$1.func_110549_a(ClientProxy.java:77)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110542_a(SimpleReloadableResourceManager.java:120)
	at elec332.core.client.model.ElecResourceManager.func_110542_a(ElecResourceManager.java:47)
	at elec332.core.proxies.ClientProxy$RenderReplacer.onRegister(ClientProxy.java:72)
	at elec332.core.client.model.ElecResourceManager.func_110542_a(ElecResourceManager.java:42)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:494)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:346)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.9
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 651167920 bytes (621 MB) / 1860173824 bytes (1774 MB) up to 5726797824 bytes (5461 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx6144m -Xms256m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.23 Powered by Forge 12.16.1.1891 73 mods loaded, 73 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCH	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCH	FML{8.0.99.99} [Forge Mod Loader] (forge-1.9-12.16.1.1891.jar) 
	UCH	Forge{12.16.1.1891} [Minecraft Forge] (forge-1.9-12.16.1.1891.jar) 
	UCH	CodeChickenCore{2.0.1.53} [CodeChicken Core] (minecraft.jar) 
	UCH	alt{1.02} [Additional Loot Tables] (AdditionalLootTables_1.9-1.02.jar) 
	UCH	autopackager{1.6.1} [AutoPackager] (autopackager-1.6.1.jar) 
	UCH	AutoSapling{1.3} [AutoSapling] (AutoSapling-1.3.1 MC1.9.jar) 
	UCH	basemetals{2.2.2} [Base Metals] (BaseMetals_1.9-2.2.2.jar) 
	UCH	Baubles{1.2.0.2} [Baubles] (Baubles-1.9-1.2.0.2.jar) 
	UCH	bdlib{1.11.0.14} [BD Lib] (bdlib-1.11.0.14-mc1.9.jar) 
	UCH	betterbuilderswands{0.6.0} [Better Builder's Wands] (BetterBuildersWands-0.6.0-1.9r124+c748dee.jar) 
	UCH	BiomesOPlenty{4.0.2.2018} [Biomes O' Plenty] (BiomesOPlenty-1.9-4.0.2.2018-universal.jar) 
	UCH	JEI{3.3.3.197} [Just Enough Items] (jei_1.9-3.3.3.197.jar) 
	UCH	blockdrops{1.0.0} [Block Drops] (Block Drops-1.9-1.0.0.jar) 
	UCH	Bloodmoon{1.2} [Bloodmoon] (Bloodmoon-MC1.9-1.4.1.jar) 
	UCH	bookshelfapi{3.0.4} [Bookshelf] (Bookshelf-API-1.9-3.0.4.jar) 
	UCH	Chameleon{1.9-2.1.3} [Chameleon] (Chameleon-1.9-2.1.3.jar) 
	UCH	ChickenChunks{2.0.1.26} [ChickenChunks] (ChickenChunks-1.9-2.0.1.26-universal.jar) 
	UCH	chisel{@VERSION@} [Chisel] (Chisel-MC1.9-0.0.4.13.jar) 
	UCH	craftelytra{1.0} [Craftable Elytra] (CraftableElytra-1.0.jar) 
	UCH	ElecCore{1.4.270} [ElecCore] (ElecCore-1.9-1.4.270.jar) 
	UCH	deepresonance{1.1.4beta30} [DeepResonance] (deepresonance-1.9.0-1.1.4beta30.jar) 
	UCH	endercrop{1.9-1.2-1836} [Ender Crop] (endercrop-1.9.1.3.jar) 
	UCH	enderthing{0.6.6} [Enderthing] (enderthing-1.9-0.6.6.jar) 
	UCH	enderutilities{0.5.3} [Ender Utilities] (enderutilities-1.9-0.5.3.jar) 
	UCH	fastleafdecay{1.6} [Fast Leaf Decay] (FastLeafDecay-1.9-1.6.jar) 
	UCH	FlatBedrockx{1.2.0} [FlatBedrock Xplosion's Edition] (FlatBedrock-1.2.0_1.9.jar) 
	UCH	fluxducts{1.0.3} [Flux Ducts] (fluxducts-mc1.9-1.0.3.jar) 
	UCH	SilentLib{1.0.5} [Silent Lib] (SilentLib-1.9-1.0.5-11.jar) 
	UCH	FunOres{1.2.4} [Fun Ores] (FunOres-1.9-1.2.4-63.jar) 
	UCH	advgenerators{0.9.20.8} [Advanced Generators] (generators-0.9.20.8-mc1.9.jar) 
	UCH	grapple_hooks{1.0.7} [Grapple Hooks] (Grapple Hooks-1.9-1.0.7.jar) 
	UCH	graves{1.9-b10-universal} [Graves Mod] (graves-1.9-b10-universal.jar) 
	UCH	HardcoreDarkness{1.8} [Hardcore Darkness] (HardcoreDarkness-MC1.9-1.8.jar) 
	UCH	hopperducts{1.4.7} [Hopper Ducts] (hopperducts-mc1.9-1.4.7.jar) 
	UCH	inventorytweaks{1.61-dev-49-c5b6395} [Inventory Tweaks] (InventoryTweaks-1.61-dev-49.jar) 
	UCH	journeymap{1.9-5.2.0b1} [JourneyMap] (journeymap-1.9-5.2.0b1-unlimited.jar) 
	UCH	jeresources{0.4.5.27} [Just Enough Resources] (JustEnoughResources-1.9-0.4.5.27.jar) 
	UCH	jet_packs{1.0.0} [Just JetPacks] (JustJetpacks-1.0.0.jar) 
	UCH	llor{1.0.7-mc1.9} [Light Level Overlay Reloaded] (LLOverlayReloaded-1.0.7-mc1.9.jar) 
	UCH	Login_Shield_MC1.9{1.2-21-g08fa29a} [Login Shield] (Login_Shield_MC1.9-1.2-21-g08fa29a.jar) 
	UCH	lycanitesmobs{1.14.0.0 - MC 1.9.0} [Lycanites Mobs] (LycanitesMobsComplete 1.14.0.0 ALPHA02 [1.9.0].jar) 
	UCH	forestmobs{1.14.0.0 - MC 1.9.0} [Lycanites Forest Mobs] (LycanitesMobsComplete 1.14.0.0 ALPHA02 [1.9.0].jar) 
	UCH	freshwatermobs{1.14.0.0 - MC 1.9.0} [Lycanites Freshwater Mobs] (LycanitesMobsComplete 1.14.0.0 ALPHA02 [1.9.0].jar) 
	UCH	plainsmobs{1.14.0.0 - MC 1.9.0} [Lycanites Plains Mobs] (LycanitesMobsComplete 1.14.0.0 ALPHA02 [1.9.0].jar) 
	UCH	swampmobs{1.14.0.0 - MC 1.9.0} [Lycanites Swamp Mobs] (LycanitesMobsComplete 1.14.0.0 ALPHA02 [1.9.0].jar) 
	UCH	mantle{1.9-0.9.4.jenkins114} [Mantle] (Mantle-1.9-0.9.4.jar) 
	UCH	MikeDongles{1.9-0.0.4} [Mike Dongles] (MikeDongles-1.9-0.0.4.jar) 
	UCH	Morpheus{1.9-3.0.2} [Morpheus] (Morpheus-1.9-3.0.2.jar) 
	UCH	tconstruct{1.9-2.2.2.jenkins156} [Tinkers' Construct] (TConstruct-1.9-2.2.2.jar) 
	UCH	neotech{3.0.6} [NeoTech] (NeoTech-1.9-3.0.6.jar) 
	UCH	nethermetals{1.0.4} [Nether Metals] (NetherMetals-1.0.4.jar) 
	UCH	netherportalfix{1.0} [Nether Portal Fix] (netherportalfix-mc1.9-3.0.6.jar) 
	UCH	harvestcraft{1.9a} [Pam's HarvestCraft] (Pam's HarvestCraft 1.9a.jar) 
	UCH	portablecrafting{1.9-1.0} [Portable Crafting] (PortableCrafting-1.9-1.0.jar) 
	UCH	progressiveautomation{1.6.42} [Progressive Automation] (ProgressiveAutomation-1.9-1.6.42.jar) 
	UCH	quantumflux{2.0.6} [QuantumFlux] (quantumflux-1.9-2.0.6.jar) 
	UCH	randomthings{3.7} [Random Things] (RandomThings-MC1.9-3.7.jar) 
	UCH	reap{1.0.4} [Reap Mod] (ReapMod 1.0.4.jar) 
	UCH	reborncore{2.1.0.53} [RebornCore] (RebornCore-1.9-2.1.0.53-universal.jar) 
	UCH	ResourcefulCrops{1.9-1.3.1-47} [ResourcefulCrops] (ResourcefulCrops-1.9-1.3.1-47.jar) 
	UCH	rftools{4.46} [RFTools] (rftools-1.9.0-4.46.jar) 
	UCH	rftoolsdim{4.23beta37} [RFTools Dimensions] (rftoolsdim-1.9.0-4.23beta37.jar) 
	UCH	Roguelike{1.5.0} [Roguelike Dungeons] (RoguelikeDungeons-1.9-1.5.0.jar) 
	UCH	shadowmc{3.1.0} [ShadowMC] (ShadowMC-1.9-3.1.4.jar) 
	UCH	SleepingBag{1.1.0} [Sleeping Bag] (SleepingBag-1.9-1.1.0.jar) 
	UCH	StorageDrawers{1.9-3.1.6} [Storage Drawers] (StorageDrawers-1.9-3.1.6.jar) 
	UCH	Trashcans{2.0.2} [Trashcans] (Trashcans-1.9-2.0.2.jar) 
	UCH	CaveCraft{@VERSION@} [TSON Craft] (TSON Craft 2.6.3.jar) 
	UCH	Waila{1.7.0} [Waila] (Waila-1.7.0-B2_1.9.jar) 
	UCH	WailaHarvestability{1.1.7} [Waila Harvestability] (WailaHarvestability-mc1.9-1.1.7.jar) 
	UCH	ICSE{1.0.0.0} [I Can See Everything] (Wawla-1.9-2.2.0.186.jar) 
	UCH	wawla{2.2.0.178} [What Are We Looking At] (Wawla-1.9-2.2.0.186.jar) 
	Loaded coremods (and transformers): 
CodeChickenCorePlugin (CodeChickenCore-1.9-2.0.1.53-universal.jar)
  codechicken.core.asm.TweakTransformer
  codechicken.core.asm.DelegatedTransformer
  codechicken.core.asm.DefaultImplementationTransformer
FldLoadingPlugin (FastLeafDecay-1.9-1.6.jar)
  com.olafski.fastleafdecay.FldTransformer
LoadingPlugin (HardcoreDarkness-MC1.9-1.8.jar)
  lumien.hardcoredarkness.asm.ClassTransformer
LoadingPlugin (RandomThings-MC1.9-3.7.jar)
  lumien.randomthings.asm.ClassTransformer
Reborn Core ASM (RebornCore-1.9-2.1.0.53-universal.jar)
  reborncore.asm.RebornClassTransformer
CCCDeobfPlugin (unknown)
  
FMLPlugin (InventoryTweaks-1.61-dev-49.jar)
  invtweaks.forge.asm.ContainerTransformer
LoadingPlugin (Bloodmoon-MC1.9-1.4.1.jar)
  lumien.bloodmoon.asm.ClassTransformer
CCLCorePlugin (CodeChickenLib-1.9-2.0.1.23-universal.jar)
  codechicken.lib.asm.ClassHeirachyManager
  codechicken.lib.asm.RenderHookTransformer
	GL info: ' Vendor: 'Intel' Version: '3.1.0 - Build 9.17.10.3347' Renderer: 'Intel(R) HD Graphics'
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)

	List of loaded APIs: 
		* Baubles|API (1.1.1.0) from Baubles-1.9-1.2.0.2.jar
		* ChiselAPI (0.0.1) from Chisel-MC1.9-0.0.4.13.jar
		* ChiselAPI|Carving (0.0.1) from Chisel-MC1.9-0.0.4.13.jar
		* CoFHAPI (1.8.9R1.2.0B1) from quantumflux-1.9-2.0.6.jar
		* CoFHAPI|block (1.8.9R1.2.0B1) from ProgressiveAutomation-1.9-1.6.42.jar
		* CoFHAPI|energy (1.8.9R1.2.0B1) from mcjtylib-1.9.0-1.8.3.jar
		* CoFHAPI|tileentity (1.8.9R1.2.0B1) from ProgressiveAutomation-1.9-1.6.42.jar
		* DR-API (1.0.4-Beta) from deepresonance-1.9.0-1.1.4beta30.jar
		* ElecCore|Abilities (#API_VER#) from ElecCore-1.9-1.4.270.jar
		* FunOresAPI (3) from FunOres-1.9-1.2.4-63.jar
		* IC2API (1.0) from RebornCore-1.9-2.1.0.53-universal.jar
		* jeresources|API (0.4.5.27) from JustEnoughResources-1.9-0.4.5.27.jar
		* journeymap|client-api (1.2-SNAPSHOT) from journeymap-1.9-5.2.0b1-unlimited.jar
		* journeymap|client-api-display (1.2-SNAPSHOT) from journeymap-1.9-5.2.0b1-unlimited.jar
		* journeymap|client-api-event (1.2-SNAPSHOT) from journeymap-1.9-5.2.0b1-unlimited.jar
		* journeymap|client-api-model (1.2-SNAPSHOT) from journeymap-1.9-5.2.0b1-unlimited.jar
		* journeymap|client-api-util (1.2-SNAPSHOT) from journeymap-1.9-5.2.0b1-unlimited.jar
		* JustEnoughItemsAPI (3.1.0) from jei_1.9-3.3.3.197.jar
		* McJtyLib (1.9.0-1.8.3) from mcjtylib-1.9.0-1.8.3.jar
		* reborncoreAPI (2.1.0.53) from RebornCore-1.9-2.1.0.53-universal.jar
		* ResourcefulCrops|API (1.9-1.3.1-47) from ResourcefulCrops-1.9-1.3.1-47.jar
		* StorageDrawersAPI (1.7.10-1.2.0) from StorageDrawers-1.9-3.1.6.jar
		* StorageDrawersAPI|config (1.7.10-1.2.0) from StorageDrawers-1.9-3.1.6.jar
		* StorageDrawersAPI|event (1.7.10-1.2.0) from StorageDrawers-1.9-3.1.6.jar
		* StorageDrawersAPI|inventory (1.7.10-1.2.0) from StorageDrawers-1.9-3.1.6.jar
		* StorageDrawersAPI|pack (1.7.10-1.2.0) from StorageDrawers-1.9-3.1.6.jar
		* StorageDrawersAPI|registry (1.7.10-1.2.0) from StorageDrawers-1.9-3.1.6.jar
		* StorageDrawersAPI|render (1.7.10-1.2.0) from StorageDrawers-1.9-3.1.6.jar
		* StorageDrawersAPI|storage (1.7.10-1.2.0) from StorageDrawers-1.9-3.1.6.jar
		* StorageDrawersAPI|storage-attribute (1.7.10-1.2.0) from StorageDrawers-1.9-3.1.6.jar
		* WailaAPI (1.3) from Waila-1.7.0-B2_1.9.jar
	Launched Version: forge-12.16.1.1891
	LWJGL: 2.9.4
	OpenGL: Intel(R) HD Graphics GL version 3.1.0 - Build 9.17.10.3347, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: No
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 2x Intel(R) Pentium(R) CPU B960 @ 2.20GHz

**Comment by Elec332** [comment]
You should install MCMultiPart to fix this.

**Comment by Elec332** [comment]
This is a dependancy mistake, but MCMP will PR'd to Forge soonTM

**Comment by popps73x** [comment]
thank you the multipart fixed it.
